export const Routes = {
  Dashboard: '/',
  Setup: '/setup',
  Welcome: '/welcome',
  Customers: '/customers',
  Suppliers: '/suppliers',
  Products: '/products',
  CatalogSettings: '/catalog-settings',
  Inventory: '/inventory',
  Purchases: '/purchases',
  CustomerOrders: '/customer-orders',
  Sales: '/sales',
  Treasury: '/treasury',
  Settings: '/settings',
} as const;