export const Routes = {
  Dashboard: '/',
  Setup: '/setup',
  Welcome: '/welcome',
  Customers: '/customers',
  Suppliers: '/suppliers',
  Products: '/products',
  CatalogSettings: '/catalog-settings',
  Inventory: '/inventory',
  InventoryClearance: '/inventory/clearance',
  Purchases: '/purchases',
  PurchasesLots: '/purchases/lots',
  CustomerOrders: '/customer-orders',
  Sales: '/sales',
  SalesPayments: '/sales/payments',
  Treasury: '/treasury',
  TreasuryCycles: '/treasury/cycles',
  Settings: '/settings',
} as const;
