// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangePassword(arg1, arg2, arg3) {
  return window['go']['bindings']['App']['ChangePassword'](arg1, arg2, arg3);
}

export function Context() {
  return window['go']['bindings']['App']['Context']();
}

export function GetAllSettings() {
  return window['go']['bindings']['App']['GetAllSettings']();
}

export function GetAppSettings() {
  return window['go']['bindings']['App']['GetAppSettings']();
}

export function GetAuditLog(arg1, arg2, arg3) {
  return window['go']['bindings']['App']['GetAuditLog'](arg1, arg2, arg3);
}

export function GetBusinessInfo() {
  return window['go']['bindings']['App']['GetBusinessInfo']();
}

export function GetConnectionConfig() {
  return window['go']['bindings']['App']['GetConnectionConfig']();
}

export function GetCurrencies() {
  return window['go']['bindings']['App']['GetCurrencies']();
}

export function GetModules() {
  return window['go']['bindings']['App']['GetModules']();
}

export function GetPreferences() {
  return window['go']['bindings']['App']['GetPreferences']();
}

export function GetProfile(arg1) {
  return window['go']['bindings']['App']['GetProfile'](arg1);
}

export function GetTaxes() {
  return window['go']['bindings']['App']['GetTaxes']();
}

export function Init() {
  return window['go']['bindings']['App']['Init']();
}

export function Login(arg1) {
  return window['go']['bindings']['App']['Login'](arg1);
}

export function Logout(arg1) {
  return window['go']['bindings']['App']['Logout'](arg1);
}

export function SaveAppSettings(arg1) {
  return window['go']['bindings']['App']['SaveAppSettings'](arg1);
}

export function SaveConnectionConfig(arg1) {
  return window['go']['bindings']['App']['SaveConnectionConfig'](arg1);
}

export function SetModuleEnabled(arg1, arg2) {
  return window['go']['bindings']['App']['SetModuleEnabled'](arg1, arg2);
}

export function Shutdown(arg1) {
  return window['go']['bindings']['App']['Shutdown'](arg1);
}

export function Startup(arg1) {
  return window['go']['bindings']['App']['Startup'](arg1);
}

export function TestDatabaseConnection(arg1) {
  return window['go']['bindings']['App']['TestDatabaseConnection'](arg1);
}

export function UpdateBusinessInfo(arg1) {
  return window['go']['bindings']['App']['UpdateBusinessInfo'](arg1);
}

export function UpdatePreference(arg1, arg2) {
  return window['go']['bindings']['App']['UpdatePreference'](arg1, arg2);
}

export function UpdateProfile(arg1, arg2) {
  return window['go']['bindings']['App']['UpdateProfile'](arg1, arg2);
}

export function ValidateSession(arg1) {
  return window['go']['bindings']['App']['ValidateSession'](arg1);
}
