// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Context() {
  return window['go']['bindings']['App']['Context']();
}

export function Shutdown(arg1) {
  return window['go']['bindings']['App']['Shutdown'](arg1);
}

export function Startup(arg1) {
  return window['go']['bindings']['App']['Startup'](arg1);
}
