// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {bindings} from '../models';

export function ChangePassword(arg1:string,arg2:string,arg3:string):Promise<void>;

export function Context():Promise<context.Context>;

export function GetAllSettings():Promise<Record<string, any>>;

export function GetAppSettings():Promise<bindings.AppSettingsDTO>;

export function GetAuditLog(arg1:number,arg2:number,arg3:string):Promise<bindings.AuditLogResult>;

export function GetBusinessInfo():Promise<bindings.BusinessInfoDTO>;

export function GetConnectionConfig():Promise<bindings.ConnectionConfigDTO>;

export function GetCurrencies():Promise<Array<bindings.CurrencyDTO>>;

export function GetModules():Promise<Array<bindings.ModuleDTO>>;

export function GetPreferences():Promise<bindings.PreferencesDTO>;

export function GetProfile(arg1:string):Promise<bindings.ProfileDTO>;

export function GetTaxes():Promise<Array<bindings.TaxDTO>>;

export function Init():Promise<void>;

export function Login(arg1:bindings.LoginRequest):Promise<bindings.LoginResponse>;

export function Logout(arg1:string):Promise<void>;

export function SaveAppSettings(arg1:bindings.AppSettingsDTO):Promise<void>;

export function SaveConnectionConfig(arg1:bindings.ConnectionConfigDTO):Promise<void>;

export function SetModuleEnabled(arg1:string,arg2:boolean):Promise<void>;

export function Shutdown(arg1:context.Context):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function TestDatabaseConnection(arg1:bindings.ConnectionConfigDTO):Promise<string>;

export function UpdateBusinessInfo(arg1:bindings.BusinessInfoDTO):Promise<void>;

export function UpdatePreference(arg1:string,arg2:string):Promise<void>;

export function UpdateProfile(arg1:string,arg2:bindings.ProfileDTO):Promise<void>;

export function ValidateSession(arg1:string):Promise<boolean>;
