// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {bindings} from '../models';
import {config} from '../models';
import {logger} from '../models';

export function Bindings():Promise<bindings.App>;

export function Config():Promise<config.Config>;

export function Logger():Promise<logger.Logger>;
