// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Bindings() {
  return window['go']['main']['App']['Bindings']();
}

export function Config() {
  return window['go']['main']['App']['Config']();
}

export function Logger() {
  return window['go']['main']['App']['Logger']();
}
